import socket
from ipaddress import IPv4Address, IPv4Network, IPv6Address, IPv6Network
from collections.abc import Iterator
from typing import overload

type NetworkKey = str | IPv4Network | IPv6Network
type AddressKey = str | IPv4Address | IPv6Address | IPv4Network | IPv6Network

class Pattrie:
    def __init__(
        self,
        maxbits: int = 32,
        family: int = socket.AF_INET,
    ) -> None: ...

    @overload
    def insert(self, prefix: NetworkKey, value: object) -> None: ...
    @overload
    def insert(self, addr: AddressKey, prefixlen: int, value: object) -> None: ...

    def __setitem__(self, key: NetworkKey, value: object) -> None: ...
    def __getitem__(self, key: AddressKey) -> object: ...
    def __delitem__(self, key: NetworkKey) -> None: ...
    def __contains__(self, key: AddressKey) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...

    def get(self, key: AddressKey, default: object = None) -> object: ...
    def get_many(self, keys: list[AddressKey], default: object = None) -> list[object]: ...
    def get_many(self, keys: list[AddressKey], default: object = None) -> list[object]: ...
    def get_key(self, key: AddressKey) -> str | None: ...
    def has_key(self, key: NetworkKey) -> bool: ...
    def delete(self, key: NetworkKey) -> None: ...
    def keys(self) -> list[str]: ...
    def freeze(self) -> None: ...
    def thaw(self) -> None: ...
